### ISSUE TITLE
Restore from Backup instructions

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/bar-assistant#107]
I see backup instructions on this page.....but no commands are given to restore. I'm looking to share my entire database with others for them to use. Could you update your docs page? Thanks.

https://bar-assistant.github.io/docs/setup/backups/

**Comment by karlomikus** [comment]
Thanks, the docs need updating.
In the meantime you can use the following command to get shareable .zip file:
```
$ docker compose exec bar-assistant php artisan bar:export-zip
```

Then when you want to import from this file you just put it in your bar-assistant volume and run
```
$ docker compose exec bar-assistant php artisan bar:import
```

**Comment by zhdenny** [comment]
When I run the export command to output the .zip file.....this is the output message:

```
Export created successfully at "/var/www/cocktails/storage/bar-assistant/ba_export_2023-05-18-02-03-47.zip". Please note this will only create a zip file that will hel
p you import data into a new BA instance. For a complete backup you should manually backup your uploads folder and database!
```

What defines a "new BA instance"? By default, aren't all BA instances pre-populated with your default database? What happens if another user runs this command on their BA instance which is not new?

**Comment by karlomikus** [comment]
If you do an import on an existing instance, it will overwrite data related to cocktails, ingredients, glasses, images, etc. Basically all the data that can be considered shareable, so user data for example will not be exported/imported.
