### ISSUE TITLE
Instructions & Garnish sections not updating

### ISSUE THREAD

**Issue by TheSpoon98** [karlomikus/bar-assistant#108]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
Instructions & Garnish sections of cocktail page do not update when navigating from another cocktail.

**To Reproduce**
Navigate to a cocktail.
Open search (Ctrl-K or clicking the menu both produced same results)
Search for and navigate to another cocktail
Image/Description/Tags/etc all update - Instructions & Garnish sections still display information from prior cocktail.

**Versions:**
 - Docker: 20.10.21
 - Browser: Chrome, Firefox
 - Salt Rim: v1.10.0
 - Bar Assistant: v1.10.2
 - Meilisearch: 1.1.1

**Additional context, log outputs...**
No errors in logs noticed.

**Comment by TheSpoon98** [comment]
And I just realized this might belong to the salt-rim repo.  Let me know if I should close and reproduce it there.

**Comment by zhdenny** [comment]
This is the same as this I believe (Stupifier here)

https://github.com/karlomikus/vue-salt-rim/issues/73

**Comment by TheSpoon98** [comment]
Yeah - I closed this one after finding it.
