### ISSUE TITLE
[Feature Request] Perfect Scraping from a Bar-Assistant / SaltRim shared cocktail

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/bar-assistant#112]
Bar Assistant setup A shares a cocktail. The share URL is generated.

Bar Assistant setup B provides the shared URL to the cocktail scraper. Will the cocktail scraped perform a perfect scrape? Import Description, Photo, Ingredients, Instructions, Garnish, Tags, etc?

If not, can it? It would be a nice feature if your cocktail scraper tool 100% supports the shared URLs bar-assistant can generate.

**Comment by karlomikus** [comment]
Yeah, this is planned in https://github.com/karlomikus/vue-salt-rim/issues/9 for salt-rim

And I'm in process on refactoring how cocktails are imported so it will also come probably soon
