### ISSUE TITLE
[Docker Installation] Meilisearch API key invalid error after upgrade to 2.0

### ISSUE THREAD

**Issue by augustf** [karlomikus/bar-assistant#114]
After changing over Docker containers (and deleting the Meilisearch data) to 2.0 (Bar Assistant), 1.12.0 (Saltrim), and 1.1 (Meilisearch), everything worked except any call to Meilisearch. In my console, I see the error: MeiliSearchApiError: The provided API key is invalid.

I confirmed that MEILI_MASTER_KEY was set on the Meilisearch container, and that MEILISEARCH_KEY and MEILISEARCH_HOST were correctly set on Bar assistant. I also attempted setting those variables on SaltRim, just in case. None of this worked, and after a few rounds of confirming the key is the same across configs, I'm stuck.r

**Comment by karlomikus** [comment]
You need to [run the following command](https://bar-assistant.github.io/docs/faq/#how-do-i-update-meilisearch) after updating Meilisearch:

```bash
docker compose exec -it bar-assistant php artisan bar:refresh-user-search-keys
```

**Comment by augustf** [comment]
I'm afraid that didn't work for me.  I got a bunch of errors saying "Failed to connect to bar-search port 7700. Connection refused for https://bar-search:7700/keys. I'm able to connect to that URL, but get a message about not having a bearer token.

I assume this is because the call this script is making isn't providing a bearer token. I attempted to run MeiliSearch in development mode without a key, but it protects /keys even in that mode. I'll try to dig into what the script is doing to see if it's an operation I can perform manually.

Let me know if you had any other ideas for resolving this without data loss.

**Comment by karlomikus** [comment]
Bar Assistant communicates with Meilisearch via docker network name, so if you renamed search container you need to update `MEILISEARCH_HOST=http://bar-search:7700`.
Salt rim does not use master key to communicate with search server, instead, BA generates API key and salt rim saves that key in localstorage for use.

**Comment by augustf** [comment]
Makes sense. I was using FQDN's For these, and maybe that's where I got into trouble, with only container re-creation allowing me to move forward. But the update script seemed to use port 7700, regardless of what port the environment variable specified.
