### ISSUE TITLE
Add support for other database engines (PostgreSQL, MySQL)

### ISSUE THREAD

**Issue by sbordeyne** [karlomikus/bar-assistant#121]
SQLite is cool as a prototype, but Postgres or MySQL are both more mature and feature complete as SQL databases. It would be great to connect bar assistant to a CNPG (cloud native postgresql) instance in my kube setup.

**Comment by karlomikus** [comment]
This should be pretty straightforward to implement, it just needs a few tweaks to docker entrypoint.

Thanks

**Comment by virtualdxs** [comment]
I'd really like to see this feature; I run most of my stuff on NFS and SQLite does not play nicely. I've standardized on Postgres for everything I can.
