### ISSUE TITLE
[Feature Request] Volume tracker in ingredients and "I made X cocktail" button on cocktail page

### ISSUE THREAD

**Issue by Dogeek** [karlomikus/bar-assistant#123]
It would be a good automation to have total ingredients volume/grammage as part of the ingredient description, and automatically decrease the amount available based on the cocktails you make, displaying a "running low" notification when the ingredient's running out.

**Comment by zhdenny** [comment]
This would require a user to measure all of their current open bottles and record that value in Bar Assistant. Seems like a ton of work. I think I have over 100 open bottles currently 😐

**Comment by karlomikus** [comment]
This would be a cool feature but I think it's out of scope currently for this project. I want to include features that are more useful for a smaller home bar instead of some sort of inventory tracking.

Thanks
