### ISSUE TITLE
Add ingredient scraping from retailers

### ISSUE THREAD

**Issue by sbordeyne** [karlomikus/bar-assistant#125]
There's a few supermarkets / liquor store chains where I live, and it would be great to be able to scrape ingredients as we do cocktails

Scraping would include :

- Link to store page ( #122 )
- Ingredient Photo
- Name
- Description
- Origin
- ABV%
- Category (Based on the defaults, Liqueur, Spirit, Wine)
- Sub Category (i.e. using the parent ingredient feature to categorize rhums, whiskies, scotches, etc)

**Comment by karlomikus** [comment]
This would be cool but I'm not what would be the best way to implement it. For cocktail recipes a lot of webpages use linked data like json+ld and it's straightforward to scrape that data.
Seems like ingredient scraping would also heavily depend on where in the world you live and what liquor stores are available.

Can you post a few websites from which you would want to import data?

**Comment by Dogeek** [comment]
I'm french, so this includes 
- https://nicolas.com
- https://e.leclerc
- https://www.carrefour.fr
- https://auchan.fr

Those are the main ones. Maybe amazon also has alcohol buying options ? That could be a good idea
