### ISSUE TITLE
[Feature Request] Add extra default categories

### ISSUE THREAD

**Issue by Dogeek** [karlomikus/bar-assistant#126]
- Sauces (tabasco, worcestershire sauce)
- Herbs (Mint, Basil)
- Spices (Salt, Sugar, Cinnamon, Nutmeg, Pepper)

**Comment by zhdenny** [comment]
I think the idea is the default setup is just to give you ideas. Your can modify it all however your want, you just need to put in the time.

My setup is dramatically different then the default setup. I have already heavily modified everything with a large amount of categories and parent/child ingredients like this.

The standard user is probably fine with the default setup... And users have the ability to change anything themselves if they want more/less

**Comment by karlomikus** [comment]
I don't want to complicate the initial data that bar assistant comes with too much. Users can freely edit and modify the default ingredients how they want so I don't think this is needed.

Thanks!

**Comment by Dogeek** [comment]
Is there a way to mount a yaml file to redefine the default ingredients/cocktails as of right now ?

**Comment by zhdenny** [comment]
See the export/import feature in link below. It is in pretty simple JSON format that you could work with.

https://bar-assistant.github.io/docs/setup/backups/

**Comment by karlomikus** [comment]
You can checkout how ingredients and categories are built for new instances here: https://github.com/karlomikus/bar-assistant/blob/master/app/Console/Commands/BarOpen.php#L129

Also exporting to json, editing and importing, as zhdenny described, is also viable.
