### ISSUE TITLE
Add required ustensils to make a cocktail

### ISSUE THREAD

**Issue by Dogeek** [karlomikus/bar-assistant#127]
Defaults could include :

- Mixing glass
- Shaker (Boston or Tumbler)
- Bar spoon
- Julep Strainer
- Hawthorne strainer
- Atomizer (Spray bottle)
- Muddler
- Jigger
- Cocktail Smoker
- Fine mesh strainer
- Zester
- Channel Knife
- Y Peeler
- Bar knife
- Ice carving knife ?

**Comment by Dogeek** [comment]
There could even be amazon/barfly/cocktail kingdom affiliate links to support this project for the relevant tools 😄

**Comment by zhdenny** [comment]
I think this would be a nice feature to have as long as the tools list is editable. Great idea
