### ISSUE TITLE
Donate Link/Button for Developer

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/bar-assistant#129]
You work so hard on this. How can I donate to you?
I do not want you to feel burned out. I appreciate your dedication.

Please include a donate link on your GitHub page..... Or maybe a small donate Button in the Salt Rim app.

**Comment by karlomikus** [comment]
Thanks for the interest but I do this in my free time, and I don't stress about it too much :). I don't really have the need for donations right now, but I'm really glad you are enjoying it!

Thanks for all the feedback!
