### ISSUE TITLE
BAR_NAME and BAR_DESCRIPTION have no effect

### ISSUE THREAD

**Issue by superfunk2000** [karlomikus/bar-assistant#131]
The (optional) parameters BAR_NAME and BAR_DESCRIPTION have no effect on the appearance
```
.
.
.
# (Optional) Bar name
BAR_NAME=My.bar

# (Optional) Short bar description
BAR_DESCRIPTION=Professional Drinking Etablissement
```
Shouldn't that change?
![image](https://github.com/karlomikus/bar-assistant/assets/90634124/26f84d53-d4e2-45d9-915c-cb12a9f392d8)

Salt Rim: v1.15.0
Bar Assistant: v2.1.0
Meilisearch: 1.2.0

**Comment by zhdenny** [comment]
See here for your solution:
https://github.com/karlomikus/vue-salt-rim/issues/68

**Comment by superfunk2000** [comment]
Oh - Thank you for the Hint!
