### ISSUE TITLE
Strange reaction of the ingredient filter

### ISSUE THREAD

**Issue by superfunk2000** [karlomikus/bar-assistant#134]
There seems to be an issue with the ingredient filter.
I added cucumber syrup to the ingredients.
If I search for it now, he only finds it when I enter "cocum". Not before ("cocu").
Whether in the search for ingredients or when creating a new cocktail.

![2023-06-28 08_58_37-Ingredients ⋅ Salt Rim und 14 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/karlomikus/bar-assistant/assets/90634124/1a1d36c7-5e2e-4b3d-bff3-d758bbe459a1)
![2023-06-28 08_58_52-Ingredients ⋅ Salt Rim und 14 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/karlomikus/bar-assistant/assets/90634124/ffee99cc-9b57-46fc-98a5-9fe62cb10b54)

Is it wanted like that?

**Comment by zhdenny** [comment]
"Cucumber" doesn't contain the letter "o"........

**Comment by karlomikus** [comment]
This is related to the [typo tolerance of Meilisearch](https://www.meilisearch.com/docs/learn/configuration/typo_tolerance#configuring-typo-tolerance).

> If the query word is between 1 and 4 characters, no typo is allowed. Only documents that contain words that start with or are of the same length with this query word are considered valid

**Comment by superfunk2000** [comment]
Sorry there was a typo in the tag.
