### ISSUE TITLE
Develop chrome/firefox extension to scrape data from a single click

### ISSUE THREAD

**Issue by sbordeyne** [karlomikus/bar-assistant#135]
Pretty straightforward, we could have a simple extension that makes API calls to a configurable bar assistant server to start scraping a site.

The scraped data would be held in queue until an admin manually approves / edits the scrapped data.

**Comment by karlomikus** [comment]
I like this idea, although it could probably be done via bookmarklet instead of creating a whole new extension.

**Comment by Dogeek** [comment]
I think a bookmarklet would work in case of a single API call, but an extension would provide much more control, with logging in, storing the access token, handling several bar assistant instances and so on
