### ISSUE TITLE
Bar Assistant server not available with Cloudflare

### ISSUE THREAD

**Issue by f22tank** [karlomikus/bar-assistant#142]
I cannot log in because my server is not available.  Trying to set it up with a cloudflare tunnel. Web server works but it does not see the server.

**Comment by karlomikus** [comment]
I don't know what cloudflare tunnel is used for, so I can't help you with this.

**Comment by samwise22** [comment]
In my case I can reach the login page via a Cloudflare tunnel but the login button doesnt appear.

**Comment by karlomikus** [comment]
If you can't see the buttons that means that your API server is not available. I'm guessing that you need to setup cloudflare tunnel for the api instance and for meilisearch instance. If we take demo instance for example:

- https://bar.karlomikus.com - Frontend
- https://bar.karlomikus.com/bar - API server
- https://bar.karlomikus.com/search - Search server

And this is handled with nginx conf here: https://github.com/bar-assistant/docker/blob/master/nginx.conf

**Comment by samwise22** [comment]
With a cloudflare tunnel you run a piece of software called a connector on your local network and then all you configure for a given service is a mapping between a domain like barassistant.mydomain.com and [myhostIP]:3000. So there's no place to specify discreet parts of a service. 

For other self hosted services on my network (all including their own auth) I havent had to do more than the above so it's certainly possible to resolve.

Thanks for the pointer anyway, perhaps someone with more knowledge than me can figure out whats needed and if you do want to support cloudflare in the future you're probably best to set it up yourself and figure out whats going on.

Thanks again, I'm loving Bar Assistant - just want to take my recipies with me! :-)

**Comment by zhdenny** [comment]
When I reverse proxy my entire Bar Assistant setup......I had to Reverse Proxy the "webserver" docker container which is in the docker compose stack. It sounds funny but its the only way.

I would imagine Cloudflare Tunnel would be similar. The only public facing piece of Bar Assistant should be that "webserver" container. That container does all the internal communication between the various bar assistant containers.

**Comment by samwise22** [comment]
I got some help on Reddit for this, the answer is very simple. Just change the BARURL in the .env file to the external address you want to use via Cloudflare.

**Comment by NadHD** [comment]
> I got some help on Reddit for this, the answer is very simple. Just change the BARURL in the .env file to the external address you want to use via Cloudflare.

Hello, a bit later but, do you know how to make it works for BarAssistant v.3.18? I tried to change the BASE_URL into .env with bar.mydomain.com but nothing really changed, except errors when i tried to go again with localhost:3000

**Comment by giuseppebaldi** [comment]
> I got some help on Reddit for this, the answer is very simple. Just change the BARURL in the .env file to the external address you want to use via Cloudflare.

Which container did you set up in Cloudflare? I can't get this to work, returns a 502 error. I have 25 other containers working perfectly through the tunnel but can't get this one going. Was it the API server or web server (nginx) you set up there?

**Comment by giuseppebaldi** [comment]
> > I got some help on Reddit for this, the answer is very simple. Just change the BARURL in the .env file to the external address you want to use via Cloudflare.
> 
> Hello, a bit later but, do you know how to make it works for BarAssistant v.3.18? I tried to change the BASE_URL into .env with bar.mydomain.com but nothing really changed, except errors when i tried to go again with localhost:3000

Did you ever figure this out? Having some issues myself.
