### ISSUE TITLE
Email Notifications Assistance

### ISSUE THREAD

**Issue by vspaziani** [karlomikus/bar-assistant#144]
- [ X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
I can see that there is a mail.php with ENV variables but cannot figure out how to test that I have set it up correctly. Can you provide an example implementation. Once configured, is there a test button or another method to make sure that it is correct? Also, is there a password reset button that uses the users email?

**Comment by karlomikus** [comment]
This is just basic config that framework ships with. Bar Assistant is not sending any notifications yet.
