### ISSUE TITLE
"No query results for model" when opening ingredient

### ISSUE THREAD

**Issue by TheSpoon98** [karlomikus/bar-assistant#150]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
Apologies if this should be on Salt-Rim's bug list instead of bar-assistant.

When I click into some ingredients I'll receive a "No query results for model [Kami\Cocktail\Models\Ingredient]." toast error.  I've tried the scout:import from the FAQ, as well as updating Meilisearch - to no avail.

**To Reproduce**
For mine, specifically, it happens for at least white rum - however, I've done a DB import from zhdenny

**Versions:**
 - Docker: 20.10.21 (Unraid 6.11.5)
 - Browser: Chrome

**Additional context, log outputs...**
Currently running:
Salt Rim: v1.18.0
Bar Assistant: v2.4.0
Meilisearch: 1.1.1
but I believe it was occuring for me in prior versions of salt-rim and BA.

![image](https://github.com/karlomikus/bar-assistant/assets/14792646/014e60ba-88eb-4218-adcc-0fd26de8c1e6)

**Comment by karlomikus** [comment]
Try running
```
docker compose exec -it bar-assistant php artisan bar:refresh-search --clear
```

This should clear old entries that don't have references in meilisearch.

**Comment by TheSpoon98** [comment]
That did it!  Thanks.  It might be useful to toss that on the wiki/FAQ somewhere (unless you already have it and I completely missed it).  I know there's a number of people that use other people's DB backups where they'd run into this.
