### ISSUE TITLE
Permission denied for bar-assistant if not using docker volume

### ISSUE THREAD

**Issue by cbirkenbeul** [karlomikus/bar-assistant#153]
**Describe the bug**
I try to install bar-assistant in a Kubernetes environment and always get a permission denied on starting the bar-assistant container while creating the "upload" folder. I tried it on docker to double check. If I use a docker volume it works fine, but not with a mount point. It's regardless if I run the container with root privileges. 

**Additional context, log outputs...**
```
sudo docker run --name bar-assistant-app3     -p 3000:3000     -e LOG_CHANNEL=stderr     -e MEILISEARCH_HOST=http://bla:7700     -e REDIS_HOST=bla     -e ALLOW_REGISTRATION=true     -v ./barassistant:/var/www/cocktails/storage/bar-assistant     barassistant/server:v2.4.0
mkdir: cannot create directory '/var/www/cocktails/storage/bar-assistant/uploads': Permission denied
mkdir: cannot create directory '/var/www/cocktails/storage/bar-assistant/uploads': Permission denied
mkdir: cannot create directory '/var/www/cocktails/storage/bar-assistant/uploads': Permission denied
```

**Comment by zhdenny** [comment]
Permissions set to 33:33 like wiki says?

https://bar-assistant.github.io/docs/setup/
