### ISSUE TITLE
Import Database wipes Shelf

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/bar-assistant#154]
**Reproduce issue:**

1. User already has a database full of ingredients... And checkmark the ingredients they own as on their "shelf".
2. User imports a database which contains the exact same ingredients.
3. The User's "shelf" is wiped clean. User now has to mark all the ingredients user owns again.

**Desired behavior:**

The User's shelf should not be reset during a database import for ingredients which are identical between current and imported databases.

**Comment by beasthouse-au** [comment]
This happened to me. Didn't take too long to fix but painful if it happens each time.

**Comment by karlomikus** [comment]
This is how import and export currently work. It's not intended as a "backup" solution.

Before importing, the current database is wiped and the new data is imported. There is no user information in the exported data so there is no shelf/favorites/shoppinglist etc.

If you want a complete backup, currently, you will have to do it manually, by backup of the `storage/bar-assistant/database.sqlite` db file, and `storage/bar-assistant/uploads` images

**Comment by zhdenny** [comment]
I understand it is not a backup solution. I don't want it to be.

I want users who import my database daily to KEEP their user data like shelf/favorites/shopping list/etc.
It seems you already allow certain user data such as account login information to persist through imports, why not these too?
