### ISSUE TITLE
Update Docs: traefik

### ISSUE THREAD

**Issue by n1ght-hunter** [karlomikus/bar-assistant#184]
Hi would you be interested in me updates the docs to include using traefik

**Comment by karlomikus** [comment]
Hello,
Yes for sure. Docs repo is available here: https://github.com/bar-assistant/docs

**Comment by Night-Hunter-NF** [comment]
sweet will add it somtime. one nice thing is that you dont need to run nginx at all which removes a process

**Comment by anatosun** [comment]
Hey @n1ght-hunter , where can I find the docs regarding this? If you hadn't time, pasting a docker-compose would already be helpful! Thanks
