### ISSUE TITLE
Is there a community for users to share collections?

### ISSUE THREAD

**Issue by thomaseleff** [karlomikus/bar-assistant#190]
Installed bar-assistant last night, and am really excited to get started. First thing on my mind after selecting ingredients was how I can efficiently create more cocktails and ingredients.

Is there a community (e.g., discord, github) where users can share collections for recipes, or, ".json" objects for recipes and ingredients that I can POST to my application?

Thanks!

**Comment by zhdenny** [comment]
I regularly upload my entire database here for anyone to import.

https://github.com/zhdenny/bar_assistant_database

I completely overhauled the entire Ingredients/Cocktails database. Added modern cocktail classics and utilize Martin Cate Rum categories to make more detailed drink specs. Over 300 cocktails in there right now. I try to include a brief history of the drink including the original mixologist, bar, and location for each drink

**Comment by thomaseleff** [comment]
Nice! Thanks, @zhdenny, will take a look!

**Comment by samwise22** [comment]
Thanks so much for sharing.

Rather than doing this at the database level wouldnt it be easier to share a collection using the built in tools and having a JSON file you update?

I could be wrong but isnt that safer than writing over parts of our database each time? I assume the JSON importer would run validation to protect us against errors?

**Comment by zhdenny** [comment]
I use the official documentation as recommendation.

https://bar-assistant.github.io/docs/setup/backups/

Database export/import is more robust as I modified tags, categories, ingredients and cocktails. I'm not sure I can do all of that into a neat easy to export/I port package using any of the provided JSON export functions

**Comment by thomaseleff** [comment]
I took a look through the data yesterday and it looks like objects in the '.json' files within the archive could be pushed to the database using the API POST commands. Was planning to review the content and then select which to add to my database (using python to automate that workflow).

Sharing this just as an alternative approach to importing the entire database.

Based on [~/docs/setup/backups](https://bar-assistant.github.io/docs/setup/backups/), previously added shareable content like cocktails, ingredients, glasses, etc., would be deleted if not present within the 'backup' being imported.

Albeit I am just getting started, so I have very little 'manually' added content. But for those with a lot of curated content, importing another user's database may mean losing quite a bit of customization.

**Comment by zhdenny** [comment]
Yep. Anyone welcome to cut n paste anything from my database dump.

Many here simply use my database and nothing else. As I update, they update. I try to keep the ingredients and cocktails list as complete as possible but obviously it cannot contain everything. I try to avoid overly sugar/fake bar drinks and keep to standards and so-called "modern classics" by well regarded bartenders/mixologist.
