### ISSUE TITLE
Document migration from v2 to v3 when using custom database path

### ISSUE THREAD

**Issue by ovv** [karlomikus/bar-assistant#198]
- [x] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**

When using a different path than the default for the sqlite database, using the `DB_DATABASE` environment variable for example, the migration from v2 to v3 doesn't work properly.

* [2023_10_01_000001_v3.php](https://github.com/karlomikus/bar-assistant/blob/master/database/migrations/2023_10_01_000001_v3.php) fails because the v2 database exists at the destination.
* [2023_10_01_000002_migrate_v2.php](https://github.com/karlomikus/bar-assistant/blob/master/database/migrations/2023_10_01_000002_migrate_v2.php) fails because the path to the v2 database is hardcoded.

To perform a successful upgrade you need to:
1. Move your v2 database to `storage/bar-assistant/database.sqlite`
2. Run the migration

**To Reproduce**

* Install v2
* Use a custom DB_DATABASE
* Upgrade to v3

**Comment by karlomikus** [comment]
Ah yes, I'll need to make a note of that. I could  also include env var for v2 custom paths.
