### ISSUE TITLE
Update Export/Import Instructions

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/bar-assistant#204]
https://bar-assistant.github.io/docs/setup/backups/

Could this page be updated to reflect all the various Export/Import options now available. These export/import features have become rather robust and it gets a little confusing especially with the new V3 multiple bars features.

The biggest thing I want to know is the command for Exporting and Importing a specific Bar from one BarAssistant Instance to another BarAssistant Instance. Thanks!

**Comment by karlomikus** [comment]
Currently in v3 you can only do full backup via `php artisan bar:full-backup`. Exporting and importing data froma single bar will come in the next release.
