### ISSUE TITLE
Sharing shelf ingredients, shopping list between profiles within bar

### ISSUE THREAD

**Issue by lethaltank** [karlomikus/bar-assistant#212]
Enjoying this application so far!

A feature suggestion I'd like to make is to have the option to use a single, unified shelf ingredients and shopping list across profiles within a bar. As a use case, my fiance and I both make drinks at our home bar. We want to have separate profiles in the bar so that we can each have our own ratings and favorite cocktails, but this requires us to each separately track our shelf ingredients as we add and use up bottles and to need to reconcile our shopping lists.

Would it be possible to have a setting for the bar that causes all profiles for that bar to share the same shelf ingredients and shopping list? Thanks!

**Comment by karlomikus** [comment]
There is no feature like that planned.

What you can do currently is have a single user manage the shelf for the bar and use the `Make cocktails in my shelf public to all bar members` option in profile to make the shelf public.
