### ISSUE TITLE
What is the current method to populate the initial cocktails/ingredients/glasses/utensils?

### ISSUE THREAD

**Issue by justingood** [karlomikus/bar-assistant#223]
I'm testing bar-assistant using docker-compose, but when creating a new bar it has no data.

After searching, I found https://github.com/karlomikus/bar-assistant/issues/176 which recommends running `php artisan bar:open` . However, that fails with:
```
ERROR  Command "bar:open" is not defined.
```

This command appears to have been removed in https://github.com/karlomikus/bar-assistant/commit/344678a0befa01b7bcb2188223592fb3579aa043 in preparation for the v3.0 release.

What is the current method for populating an empty instance with the default data?

Thanks!

**Comment by karlomikus** [comment]
When creating a new bar you can select what data gets imported. In salt rim you can use the available checkboxes, via API you can add "options" attribute like in the docs.

```
{
  "name": "My bar name",
  "subtitle": "The awesome bar",
  "description": "A bar at the end of the town",
  "enable_invites": true,
  "options": [
    "cocktails",
    "ingredients"
  ]
}
```

**Comment by justingood** [comment]
Thank you, after deleting and starting again from scratch, that works!

In retrospect, I'm not at all sure how I got it into a state where it had nothing since those check-boxes are defaulted :facepalm:  Either way, all good now!
