### ISSUE TITLE
Exclude cocktails by ingredient

### ISSUE THREAD

**Issue by daniel-simpson** [karlomikus/bar-assistant#230]
Sorry if there is already a way to do this!

Would love the ability to exclude cocktail results for a specific ingredient. E.g. I don't much like gun (sorry!) but my wife does. If I'm looking for a cocktail for me, I'd love to exclude gin cocktails.

Not sure exactly what the front end would look like, maybe some kind of label picklist? 🤷

Thanks again for the great app

**Comment by karlomikus** [comment]
Good idea, shouldn't be too hard to implement in API.
