### ISSUE TITLE
Add a Menu

### ISSUE THREAD

**Issue by mikeseese** [karlomikus/bar-assistant#248]
I want to have a public endpoint (e.g. `/menu`) that shows a subset of cocktails I can make. This differs from the shelf (which shows all cocktails I can make) and favorites (which shows some of my bar's specialties that I can't always make).

- This endpoint shouldn't require authentication so I can share it with guests so they can pick a cocktail from the menu.
- I should be able to add/remove an individual cocktail to the menu via a button/link on the cocktail details page.
- I should be able to click a button/link on a collection that sets the menu to the collection (clear the current menu and then add each cocktail in the collection). This should be a one time push/sync; it shouldn't be a constant sync (e.g. allowing me to adjust the menu if I need to add/remove things that are/aren't in the collection)
- The menu page, when visited without authentication, should only show cocktails I can make
- The menu page, when visited with authentication, should show the cocktails I can't make with some visual indicator they will be hidden (transparency, an icon, etc)
- The menu page, when visited with authentication and applicable authorization, should show a button/link by each cocktail in the list that lets me remove the cocktail from the menu

**Comment by karlomikus** [comment]
I've been thinking about the best way to make a collection public and this seems like a really good idea. Thanks!

**Comment by mikeseese** [comment]
I've started looking at creating a PR for this and I noticed that Collections belong to a BarMembership instead of a Bar, but I really envision this feature would be a singleton for a Bar. I think being able to make a collection public is a great addition, but I don't think that really addresses this feature. Making a collection public would mean that I'd have to create a dedicated "Menu" collection to make it so the link would never change, and it wouldn't really make sense to add the "set a collection's contents to this collection" feature.

I was looking at adding a `bar_menus` table that has `bar_id` and `cocktail_id` columns instead; which feels like a redundancy, but I believe it adds a unique value prop.

**Comment by karlomikus** [comment]
I'm not sure if bars should have multiple menus, and then have only 1 menu active at a single time.

**Comment by mikeseese** [comment]
Agreed that bars should only have one menu. I originally had `menu_cocktails` but wasn't sure if you preferred to have a `bar` prefix since the menu is associated with the bar.

**Comment by mikeseese** [comment]
Oh, I see what you mean. Having two tables works; I figured it could be just one table, but having 2 will be useful and prevent columns I was adding to `bars`

**Comment by mikeseese** [comment]
Thanks for implementing this @karlomikus! Sorry I didn't take this over the finish line
