### ISSUE TITLE
Ingredient consumption / amount tracking

### ISSUE THREAD

**Issue by Treygec** [karlomikus/bar-assistant#249]
Would love the ability to track how much of each ingredient I have. Adding a bottle could have an option quantity input and then a button to indicate "I made this" would consume against that amount. The "I made this" would also open up tracking for a timeline view as well as be a trigger for adding ingredients that drop below a certain volume to a shopping list.

happy to help on the vue.js side of the house but am not at all familiar with php, so would likely need some assistance there. Want to get an idea if you're onboard for this idea at all before moving forward with it.

**Comment by karlomikus** [comment]
Hello, something similar was already recommended in #219 

In general I like the idea, but I don't see people actually using this regularly after a first few times.

Keeping your shelf ingredients up to date is already expecting a lot from a user. Also you still need to somehow track common ingredients without actual liquid amount like: Lemons -> Lemon juice, limes, sodas, homemade syrups, dashes for bitters, etc.

Also this is not the quick and simple thing to implement from a backend point of view, and other features take priority.

But I do like the idea of somehow tracking what drinks you made and could possibly combine it with ingredient tracking, so I'll leave this open for now.
