### ISSUE TITLE
Collections not visible to other bar members

### ISSUE THREAD

**Issue by dari-bd** [karlomikus/bar-assistant#253]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
When other users that I invite to use my bar load the Collections screen, it is blank for them.

**To Reproduce**
Create collections in your bar. Invite other users to your bar. Have users check for the presence of collections.

**Versions:**
 - Docker: 24.0.7
 - Bar Assistant 3.7.0 and Salt Rim 2.7.0
 - Chrome 120 and Firefox 121 on Mac and Windows

**Comment by dari-bd** [comment]
One other thing to note - the Collections do show up in the filter selection for other users. Just not in the Collections page itself.

**Comment by karlomikus** [comment]
Hello,
Collections specific to bar members. Every member has his own collections. Currently you can't allow other members to change your collections.

**Comment by dari-bd** [comment]
Understood. For now we will use tags to group shared recipes instead.
