### ISSUE TITLE
Feature Request - Import via GitHub Repo URL

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/bar-assistant#259]
https://github.com/karlomikus/bar-assistant/releases/tag/v3.2.0

Ever since version 3.2.0 you provide a method to export everything to a zip file and import everything from a zip file.
The zip file follows the same structure as your GitHub bar assistant data project
https://github.com/bar-assistant/data

The default bar ingredients/cocktails are taken directly from your GitHub bar-assistant data repo.

Can there be a method to import data from a different GitHub repo if the same file/folder structure exists?

**Comment by karlomikus** [comment]
That repo gets pulled to bar assistant when [building a docker image](https://github.com/karlomikus/bar-assistant/blob/master/Dockerfile#L53) to `resources/data` folder.

One thing you can try, if you want to have a custom initial data, is to mount a new volume to that directory like this:

```
./my-initial-bar-data:/var/www/cocktails/resources/data
```

I haven't tried this but let me know if you try it and it works

**Comment by zhdenny** [comment]
Interesting but That is not quite what I am after.

I'm seeing if I can utilize GitHub's PR system against a Bar-Assistant Bar so a variety of users can contribute in a more Reviewed/Approved fashion.

And then when a new ingredient/cocktail is merged on GitHub there be a simple way for those additions/changes to propagate into active Bar-Assistant instances (either via command line or GUI).

**Comment by karlomikus** [comment]
The data repository is only used for initial bar data. Pulling new data from a github repository or any other source and syncing it into existing bars is not something that is in the scope of this project.

**Comment by zhdenny** [comment]
Ahh, I see. Ok.
Thanks for responding
