### ISSUE TITLE
Feature request: Mark cocktail with "is_done" flag

### ISSUE THREAD

**Issue by mostepunk** [karlomikus/bar-assistant#267]
Hi!
I have one more idea :)

It would be nice to have a flag if I made some cocktail or not.
For example I made some cocktail and mark it as "is_done=true" in checkbox.
And some day I want to taste some new cocktail, that I have never tried before and add to filter "is_done=false".

I think it would be nice feature.
P.S.
Sorry for my broken English :)

**Comment by karlomikus** [comment]
Hello, I think this can be currently achieved by either:
- Create a collection with done cocktails and add cocktail there
- Rate a cocktail so you kinda know that you tried it
