### ISSUE TITLE
Question: How can I remove cocktail from collection?

### ISSUE THREAD

**Issue by mostepunk** [karlomikus/bar-assistant#274]
Hi 👋🏻
I added some coctails to one of my collections. But now I want to remove one of them from collection. But I can't find how to do it correctly from WebUI.
Can you help me?

**Comment by karlomikus** [comment]
When you click on a cocktail you will have a list of collections that it belongs to and some additional options, on the right side under the "Ingredient spotlight"

**Comment by mostepunk** [comment]
@karlomikus  Thanks a lot
