### ISSUE TITLE
[Feature] Menus should only show drinks that can be made

### ISSUE THREAD

**Issue by proffalken** [karlomikus/bar-assistant#283]
It would be great if I could add a list of drinks to the menu, and then have he system only display the cocktails for which ingredients are available.

At the moment, if I'm out of an ingredient then I need to edit the menu and remove any cocktail that uses it, then add them back once the ingredient is back in stock.

It would be good to have the system handle this and "hide" any cocktail that requires an ingredient that is out of stock.

**Comment by dcwestra** [comment]
I will second this - and possibly also have the option to automatically create a menu with the on hand ingredients.

**Comment by proffalken** [comment]
> and possibly also have the option to automatically create a menu with the on hand ingredients.

Brilliant idea! If this is possible as well, then that would be amazing!

**Comment by karlomikus** [comment]
Menus are intended to be static and have prices attached to cocktails.

I'll move this feature to #288
