### ISSUE TITLE
Updating the custom URL for a Bar

### ISSUE THREAD

**Issue by proffalken** [karlomikus/bar-assistant#295]
- [ x ] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
I have renamed my bar and want to update the custom URL without having to create a new bar and re-add all the ingredients

**To Reproduce**

1. Create a new bar and call it "foo's palace"
2. Go to the bar settings and check that the bar custom URI is `http://my.install/bars/foos-palace`
3. Change the name of the bar to "Bar's Bar"
4. Observe that the custom URI remains `http://my.install/bars/foos-palace`

**Versions:**
 - Docker: N/A (running container on k3s)
 - Bar assistant: 3.12.1
 - Meliesearch: 1.6.2
 - Salt Rim: 2.12

**Comment by karlomikus** [comment]
This was intended behavior when I implemented it but I don't remember why exactly :D

I'll re-check it out once more

**Comment by proffalken** [comment]
Thanks - is there a command I can run against the database to update it in the meantime?

**Comment by karlomikus** [comment]
You can use the following sql:

```
docker compose exec bar-assistant sqlite3 storage/bar-assistant/database.ba3.sqlite "update bars set slug = 'my-new-slug' where slug = 'my-old-slug'"
```

**Comment by proffalken** [comment]
Amazing thanks!
