### ISSUE TITLE
Editing default imported glass type gives errors because of empty volume field

### ISSUE THREAD

**Issue by zeekaran** [karlomikus/bar-assistant#301]
Basically still at the fresh install state, when I go to rename Lowball it errors, preventing from saving the rename. The reason the red popup gives is that the volume field must be a number.

![image](https://github.com/user-attachments/assets/212e1400-cfc4-4759-a566-84024680d2a3)

I can create a new glass type and not enter anything into volume, and it works just fine.

**Comment by karlomikus** [comment]
Should be fixed now, thanks!
