### ISSUE TITLE
Add 'shot' unit support

### ISSUE THREAD

**Issue by skylarkbe** [karlomikus/bar-assistant#314]
This is probably a simple matter of adding the following code in the [Utils.php](https://github.com/karlomikus/bar-assistant/blob/develop/app/Utils.php#L43) calculateVolume function :
```
            if (str_starts_with($ingredient['units'], 'shot') {
                $ingredient['amount'] = $ingredient['amount'] * 44.36;
                $ingredient['units'] = 'ml';
                return $ingredient;
            }
```

**Comment by karlomikus** [comment]
Hello.
Seems like one "shot" would vary a lot depending on the size of the shot glass. I'm guessing that by that code example 1 shot = 44.36ml. How did you get that number?

Maybe this would be more suited for calculating custom units on the frontend: https://github.com/karlomikus/vue-salt-rim/issues/168

**Comment by skylarkbe** [comment]
I found it on google unit conversion ; but the issue your're pointing out is probably a far better solution.
