### ISSUE TITLE
Advanced Search Filters

### ISSUE THREAD

**Issue by Anil951** [karlomikus/bar-assistant#315]
- Enable filtering by **multiple ingredient tags simultaneously** (e.g., "citrus" and "herbal").
- Add the option to search recipes by the **creator’s user name**.
- Introduce filters for **cocktail ratings** and **specific taste profiles**.

**Comment by karlomikus** [comment]
Hello, thanks for suggestions.

- Tags are currently only supported on cocktails, so this would require implementing tags for ingredients first. I want to include more fine grained categories first, and then maybe tags will come later.
- You can already filter by users in the filters: `Recipes by user` There you can also search for specific username.
- There is already filter for user ratings and avg ratings, are there any other specific rating filtering you are missing?
- Taste profile filtering should probably be done via tags, it does not make sense to include another data field just for the taste.

**Comment by Anil951** [comment]
everything is set !! good workk..
