### ISSUE TITLE
Copy to clipboard not working

### ISSUE THREAD

**Issue by andreibrebe** [karlomikus/bar-assistant#322]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
Copying to clipboard is not working and cannot export cocktails.

**To Reproduce**
1. Go to any cocktail
2. Click share button then any "Copy as ..."
3. Attempt to paste anywhere

**Versions:**
 - Bar Assistant: 3.19.0
 - Salt Rim: 2.18.0
 - Browser: LibreWolf 121.0-1, LibreWolf 129.0.2-1, Microsoft Edge 128.0.2739.42

**Additional context, log outputs...**
Tried with multiple browsers on two computers (both running windows).
Same issue on public links for a cocktails or when creating a new API Token and clicking copy.

**Comment by karlomikus** [comment]
Hello,
[clipboard API requires secure context](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard), make sure you are running bar assistant with HTTPS enabled.
