### ISSUE TITLE
Import Broken again

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/bar-assistant#326]
On Latest Main/Stable version.

I export my bar to zip. The zip can be found [here](https://www.dropbox.com/scl/fo/a8ewhvhke4yo1594egs2u/ALOAz03aGi87Gq5BVAT1PoE?rlkey=9bcbme3xs8ltu6eki681tn6tt&e=2&dl=0)

I then try to import my bar to my test instance of bar-assistant and receive the following error:

https://logs.notifiarr.com/?e04e3fd0cb99f56b#Ctddu3zpwcPyxBCTd54GutN6k8XqTvnYSxrjbosLPEZr

**Comment by karlomikus** [comment]
Exported base tables were empty, should be fixed with new version. You will have to create a new export.
