### ISSUE TITLE
Bar-Assistant V4 - Import Broken Again

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/bar-assistant#333]
I successfully migrated/updated BarAssistant to v4 and SaltRim to v3. The new versions look/perform GREAT! But I have an issue with Export/Import.

I successfully perform a Bar Export to zip.  see screenshot.

![image](https://github.com/user-attachments/assets/1ad205d4-916b-44ca-bfd8-eacffa8cea01)

I then try to Import this zip into a separate BarAssistant/SaltRim instance which I also migrated successfully to latest versions. The zip import fails. See screenshot

![image](https://github.com/user-attachments/assets/0d26e5a5-c5a7-405c-930e-927e64bbd2a9)

Try to do a zip export and import yourself and see if you run into issues. Hopefully you can fix. Thanks!
I tried moving the zip file around to either "/var/www/cocktails" or "/var/www/cocktails/storage/bar-assistant". Nothing seemed to help. The php artisan import command would either error saying it couldn't find the zip file or show the artisan error message I have in my screenshot above.

**Comment by zhdenny** [comment]
Just some more information.

![image](https://github.com/user-attachments/assets/e4b14484-0942-4927-8394-67dcd66a44c9)

**Comment by karlomikus** [comment]
Should be fine now, wrong filepath was being checked. Thanks!

**Comment by mwweinberg** [comment]
Strangely, I'm having the exact same issue on 4.4.1.  Running `php artisan bar:import-zip BABackkup_20240328.zip` from within `/var/www/cocktails/storage/bar-assistant/backups` returns `Could not open input file: artisan`.  

Running `php artisan bar:import-recipes /var/www/cocktails/storage/bar-assistant/backups/BABackup_20240328.zip'
 from within `/var/www/cocktails` returns `File "/var/www/cocktails/storage/bar-assistant/backups/BABackup_20240328.zip" does not exist.`

**Comment by zhdenny** [comment]
I try to write the import instructions as easy as possible on my GitHub. Have you tried this? Do exactly this and it should work. The docker exec command will land you into the exact folder you need to be in to run the commands. Don't jump to different folders after you docker exec into the container.

https://github.com/zhdenny/bar_assistant_database#bar_assistant_database

**Comment by mwweinberg** [comment]
I apologize, I was trying to use the instructions here (https://docs.barassistant.app/data/).

With the new instructions I'm still getting the same error:

![Image](https://github.com/user-attachments/assets/04f3e2f8-7bed-4ef8-b95e-79c25921bdc3)

**Comment by zhdenny** [comment]
Can you docker exec without sudo? It is typically not recommended to run docker with root user. Official docker install instructions give guidance on this. Read the "Tip" area on step 3 (Looking at your screenshot I assume this is on a Pi device).

https://docs.docker.com/engine/install/raspberry-pi-os/#install-using-the-repository

After you do this, you'll also need to make sure your permissions for the files are correct.

**Comment by mwweinberg** [comment]
I've updated docker to work without sudo and re-copied the file so it has the same user permissions as everything else. However, I'm still getting the same error:

![Image](https://github.com/user-attachments/assets/652c5c15-620f-407e-ba28-b99e296b3744)

**Comment by mwweinberg** [comment]
I tried to reset everything with `docker compose pull` and 'docker compose up -d`. That worked?  The build ran in terminal. 

I then logged out of the docker shell, and re-ran `docker compose pull` and 'docker compose up -d`.

The good news is that the new bar appeared when I opened everything in the browser. The less good news is that it was totally empty.

**Comment by karlomikus** [comment]
Import paths are relative to your `/var/www/cocktails/storage/bar-assistant` folder. If you want your import to work via `php artisan bar:import-zip BABackkup_20240328.zip`, your import file should be in `/var/www/cocktails/storage/bar-assistant/BABackkup_20240328.zip`.

**Comment by zhdenny** [comment]
Ahhhh.... @karlomikus has the answer. You didn't place the import file in the bar-assistant appdata directory like the instructions say.

**Comment by mwweinberg** [comment]
(thank you both again for all of the troubleshooting help)

File is now in the correct directory:

![Image](https://github.com/user-attachments/assets/2214056d-e60e-41b1-9325-1361d476f198)

running `php artisan bar:import-zip BABackup_20240328.zip` from `/var/www/cocktails/storage/bar-assistant gets a `Could not open input file: artisan` error.

Backing out to run it from `/var/www/cocktails` triggers a `"bar:import-zip" is not defined` error:

![Image](https://github.com/user-attachments/assets/5dc64e73-2b2d-49f6-a8b4-8ac1998c802d)

Running it as `php artisan bar:import-recipes BABackup_20240328.zip` works in so much as it triggers the full build process in the terminal, but the new bar is still empty.

**Comment by zhdenny** [comment]
1. The zip must be in `/var/www/cocktails/storage/bar-assistant`. Looks like you did that.
2. The command must be run from `/var/www/cocktails`. Looks like you did that.
3. The import command is `php artisan bar:import-recipes name_of_file.zip` NOT `php artisan bar:import-zip name_of_file.zip. Looks like you tried both and eventually got it right.
4. Screenshot below is what it looks like in terminal with a successful build. I just tested this and it works for me.
5. Backup zips are only compatible with the Bar Assistant version the backup zip was made with.

![Image](https://github.com/user-attachments/assets/e1d67380-04c6-4a7c-a80d-8fcdd051f804)

![Image](https://github.com/user-attachments/assets/6844fc51-ee9b-4dc7-a503-b3e4d0a34e82)

**Comment by mwweinberg** [comment]
....and this:

`Backup zips are only compatible with the Bar Assistant version the backup zip was made with.` is the thing. Instead of updating from v3 to v4, I was just creating a clean v4 and trying to import the data I exported from v3!

I'll use the migration path described here (https://docs.barassistant.app/setup/migrate-to-40/) on the v3 version and just go from there.  I was avoiding that because I don't know anything about docker and wasn't sure if I was using Bind Mounts or Volumes. After going through this process I'm think I'm using Volumes, so I'll start with that.  

Thank you again for all of the help.  I don't know if you all are interested in this, but I would be happy to try and add more context to the documentation for people who are coming in without a strong grasp of docker (like me).  I'm not saying that because the documentation is bad - after all, I've used it to install two different versions of the app without having ever touched docker before.  However, it is clearly written with an assumption that the user will have some level of familiarity with docker.  There are good reasons to just want to keep it at that level. There are probably also some relatively small additions that would make it easier for someone who is comfortable poking around with these things but doesn't know a lot about docker.

Regardless, thank you again for the help and the great app.

**Comment by zhdenny** [comment]
Oh yes! Whole version upgrades are a big deal...very important to do that right. And FYI, Version is right around the corner.

The docker compose in my GitHub Repo. It is using bind mounts. I'm binding an internal docker path to an external path on my server.

The official documentation from the dev uses volume mounts.

And I'm sure official Documentation help is appreciated. I try to keep things really simple on my GitHub Repo instructions for people to use and import my database...but it is still easy to miss one small detail and cause issues.
