### ISSUE TITLE
Info: "405 Method Not Allowed" Error Due to Incorrect salt-rim Version in Docker Setup

### ISSUE THREAD

**Issue by fabtan** [karlomikus/bar-assistant#334]
The error that occurred was a "405 Method Not Allowed" response when attempting to send POST requests, such as registering a new account, to the Bar Assistant API. This error indicated that the server was only allowing GET and HEAD methods, blocking all POST requests.

The issue was caused by an incorrect version of the salt-rim service in the docker-compose.yml file. Although the installation was done following the provided instructions, the version was set to v2, but it needs to be v3 for proper functionality.

Solution: Update the docker-compose.yml file to use barassistant/salt-rim:v3 instead of v2. After making this change, restart the services, and the POST requests will be allowed correctly.

**Comment by karlomikus** [comment]
Thanks, fixed!
