### ISSUE TITLE
Change to API path?

### ISSUE THREAD

**Issue by reefland** [karlomikus/bar-assistant#336]
I completed my upgrade, everything is working great now.
```
Salt Rim: [v3.0.3]·Bar Assistant: [v4.0.2 ]·Meilisearch: [1.9.0]
```

But a stumbling block for me was a change I didn't see documented which could impact people using startup probes, health monitoring, etc.

With Bar Assistant `3.19.1` my startup probes referenced `:3000/api` which has worked well.  The migration guide included a port change from `3000` to `8080` so I updated my probes to use `:8080/api` but this will no longer work.  I had to change my probes to just `:8080/` and it worked. 

Not clear if this should not have worked previously, or something changed which prevents it from working now, but hopefully this helps anyone else using probes.

**Comment by reefland** [comment]
I think previously the URI `/api` would provide a code 200 with word `available` and now it returns `{"type":"api_error","message":"Endpoint not found."}` by default and I assume a non-success code.

**Comment by karlomikus** [comment]
Yeah, root path got removed in v4, but it was not documented anyway.

Good news is that the [new base image](https://serversideup.net/open-source/docker-php/docs/getting-started/default-configurations#health-checks) includes `{api_url}/healthcheck` endpoint so you can use that.

**Comment by reefland** [comment]
Perfect! This works. Thank you.
