### ISSUE TITLE
Install From Scratch (not docker) No Cocktails And Ingredients

### ISSUE THREAD

**Issue by PoeticArcher** [karlomikus/bar-assistant#341]
- [ ] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
I created a bar with 
Open bar with base cocktails
Open bar with base ingredients
But nothing appears under base cocktails or ingredients.

**Comment by karlomikus** [comment]
Hello,
It's possible that you don't have the data pulled locally.

You can run `git clone https://github.com/bar-assistant/data.git resources/data` to pull the latest cocktail/ingredient data to `resources/data` folder.

**Comment by PoeticArcher** [comment]
Thank you!
