### ISSUE TITLE
Remove/Add to Shelf Ingredient issue

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/bar-assistant#356]
Latest Version.

In SaltRim, go to Ingredients and scroll through the list. Many ingredients in the list which ARE on my shelf are shown as NOT being on my shelf for some reason.

For example, when I see Lime Juice on the ingredients page, it shows I do NOT having the ingredient in my shelf.

![Screenshot_20241107-185058.png](https://github.com/user-attachments/assets/99589348-58c3-4472-acc5-92e292e9c66e)

But when I actually click to view the Lime Juice ingredient, it in fact IS in my Shelf.

![Screenshot_20241107-185118.png](https://github.com/user-attachments/assets/de0ec398-6dfc-4cb0-814c-d4bd3be433c4)

This is just a single example, I've noticed this same behavior across many (not all) of my ingredients.

**Comment by karlomikus** [comment]
Hi,
I've just noticed I've skipped this issue.

Is this still relevant with the latest updates? I can't recreate it locally in dev or on my own instance.
