### ISSUE TITLE
Price estimation of cocktail based on ingredient prices

### ISSUE THREAD

**Issue by dlmw** [karlomikus/bar-assistant#358]
**Checklist**
- [x] I have checked that this feature is not already requested
- [x] I have checked that this feature does not already exist in the project

**Is your feature request related to a problem? Please describe.**
I have to calculate the price of the cocktail based on its ingredients manually.

**Describe the solution you'd like**
I would absolutely love to have a price estimation of the cocktail based on the price I've set for the ingredients. There can be multiple price categories and currencies, but having 2 drop-down fields on the cocktail page would solve this issue. I imagine it would help for implementation too.

**Additional context**
A prompt like this works for LLMs to give an answer:
```
I will give you the price of ingredients. I want you to tell me how much it costs to make a cocktail based on the price of ingredients (I will give you the recipe).
Jamaican rum 30ml (CHF47.78 for 70cl)
Rhum agricole 30 ml (CHF44.70 for 70cl)
Orgeat syrup 15 ml (CHF13.10 for 70cl)
Simple syrup 7.5 ml (CHF13.20 for 70cl)
Orange curacao 15 ml (CHF21.90 for 70cl)
Lime juice 30 ml (CHF0.20 for 1 lime)
```

**Comment by dlmw** [comment]
I do not wish to reopen this issue but I think this is the best place to post.

My Jamaican rum is CHF47.78 for 70cl (i.e. CHF0.068/ml). When I go to a cocktail recipe that requires 30ml, the price is not equals to CHF2.04 but CHF2.10. One could attribute this to a rounding error, but sometimes the difference between a manual calculation and the UI is CHF0.20.

Why aren't the estimations more accurate?

**Comment by karlomikus** [comment]
Currently [banker's rounding](https://github.com/brick/math/blob/0.12.0/src/RoundingMode.php#L97) is used for all calculations. So in that case CHF0.068 would become CHF0.07.

I'm still experimenting with other methods, and using [rational money](https://github.com/brick/money?tab=readme-ov-file#advanced-calculations) in future looks more inline with the manual price calculations.

**Comment by dlmw** [comment]
What about CHF1.1205 that becomes CHF1.25? I've noticed at least CHF0.10 difference once, too.
