### ISSUE TITLE
Substitutions not working

### ISSUE THREAD

**Issue by dphildebrandt** [karlomikus/bar-assistant#366]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
For example, Bourbon Whiskey is set as `Can Be Substituted With` Rye Whiskey, and Rye Whiskey is in my bar shelf. But `cocktails I can make` won't list Whiskey Sours or seem to recognize it as a substitute.

<img width="419" alt="image" src="https://github.com/user-attachments/assets/aed1db40-485b-4198-9601-076e64e2239f">

Something more generic, like a Whisky Highball, just lists the ingredient as Whiskey but doesn't seem to recognize that any kind of specific whiskey applies?

<img width="527" alt="image" src="https://github.com/user-attachments/assets/64cc810c-cdba-4af8-a8e1-1b2efdd7c3da">

**Versions:**
 - Bar Assistant: v4.1.0
 - Salt Rim: v3.4.1
 - Browser: chrome

**Comment by dphildebrandt** [comment]
Global substitutions would be a useful feature. If an ingredient (not in a cocktail recipe) says it has substitutes, it would be great to apply it instead of trying to find and editing every recipe that applies.

**Comment by ssambhi900** [comment]
Any chance this will be added any time soon? Super important feature to make it easier to match our ingredients and recipes without manually editing so many recipes!

**Comment by karlomikus** [comment]
Not planned any time soon.
You can always use ingredient hierarchy to automatically manage substitutes.

**Comment by ssambhi900** [comment]
I’ve tried it but for whatever reason my installation isn’t suggestions substitutes when viewing a recipe. I dunno what I’m doing wrong. I’ve marked ingredients as parents, enabled it in settings, but unless the recipe itself has substitutes set up, it isn’t suggesting alternates. 

For example, a recipe calling for Tequila Blanco. I added Casamigos Blanco and set its parent as Tequila Blanco. However the recipe won’t suggest Casamigos as an alternate. 

Appreciate your efforts on building such a powerful app!

**Comment by karlomikus** [comment]
Make sure you are on the latest version, there is no parent management setting anymore.

Also you need to have child ingredient in your shelf so it can show up as a substitutes. Here's an example with "Amaro" as ingredient.

<img width="875" height="276" alt="Image" src="https://github.com/user-attachments/assets/60949e9f-1b0f-437b-8f7e-b5ebe12a47c6" />

And here's how hierarchy of "Amaro" looks:

<img width="1077" height="191" alt="Image" src="https://github.com/user-attachments/assets/d9a107a8-7298-4226-8091-49f49d3d6668" />

**Comment by ssambhi900** [comment]
Thank you! Switched from v4 to dev release and all good! Love this app!!

**Comment by zhdenny** [comment]
I don't know why you jumped from v4 to dev.....v5 is the latest stable release. Just be on v5.

**Comment by ssambhi900** [comment]
I’m installing it on my Unraid server. V4 and dev are the latest versions available. I’m not sure how to install v5 on Unraid. 🙂

**Comment by zhdenny** [comment]
SaltRim is the Web UI. Latest version is v4.
Bar Assistant is the Backend. Latest version is v5.

I don't know what the Unraid Template uses but the recommended install method is docker compose, not an Unraid template. I'd recommend installing the Unraid Docker Compose plugin and following instructions for installing SaltRim/BarAssistant the official way. I have help if you need it.

I have examples in my repo here if you need help.

https://github.com/zhdenny/bar_assistant_database

**Comment by ssambhi900** [comment]
Thanks for reaching out! I installed the latest versions and hierarchy’s and everything else is working well now. 

Thank you both for contributing to such an awesome app!
