### ISSUE TITLE
Can't edit ingredients

### ISSUE THREAD

**Issue by dphildebrandt** [karlomikus/bar-assistant#367]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
When editing an ingredient in a recipe, there is no editable field.

<img width="354" alt="image" src="https://github.com/user-attachments/assets/6f50d5b9-c916-448c-b7f0-8f16092453d3">

When editing the substitute there seems to be no way to actually do it

<img width="637" alt="image" src="https://github.com/user-attachments/assets/ca6a1d24-86ca-46f4-a5ba-746c99742557">

Same with adding ingredients to recipes

<img width="628" alt="image" src="https://github.com/user-attachments/assets/53744229-59be-4d40-bf3d-7af2ff100b76">

**Versions:**
 - Bar Assistant: v4.1.0
 - Salt Rim: v3.4.1
 - Browser: Chrome

**Comment by karlomikus** [comment]
Hello,

This looks like your browser can't resolve meilisearch, can you check your browser for console/network errors and put the errors here. Usually it's an issues with missing token or url misconfiguration.

**Comment by dphildebrandt** [comment]
Yup, accidentally had meilisearch url as http, whereas rest was https, so it was disallowing mixed content. All good now!
