### ISSUE TITLE
Unable to select ingredients when adding new cocktail

### ISSUE THREAD

**Issue by gnarg** [karlomikus/bar-assistant#379]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
"Select Ingredients"  list is no longer available, replaced with `<Not selected>` message:
<img width="618" alt="Screenshot 2024-12-16 at 8 26 18 AM" src="https://github.com/user-attachments/assets/8a6fb0ac-b69a-4188-b7a9-48290f94355b" />

**To Reproduce**
Add ingredients in new cocktail form

**Versions:**
 - Bar Assistant: 4.2.4
 - Salt Rim: 3.6.3
 - Browser: Firefox

**Comment by karlomikus** [comment]
Hello, recent updates changed a few things related to search.

Can you please try steps described here: https://docs.barassistant.app/faq/#why-is-my-site-search-ingredient-search-not-working

**Comment by zhdenny** [comment]
Whenever this happens I just stop all containers then wipe Meilisearch appdata. Then fire up all containers again and it works

**Comment by gnarg** [comment]
> Hello, recent updates changed a few things related to search.
> 
> Can you please try steps described here: https://docs.barassistant.app/faq/#why-is-my-site-search-ingredient-search-not-working

This worked, thank you. I did read the FAQ, but I didn't interpret this as a search error. Thank you for your help, and thank you for all your work on this great project.
