### ISSUE TITLE
Add more filtering methods

### ISSUE THREAD

**Issue by karlomikus** [karlomikus/bar-assistant#38]
By protocol:
- Shake
- Stirred
- Build

By serving:
- Up
- Crushed ice

By strength:
Calculate ABV and use it to tag cocktail's strength
- Light
- Medium
- Strong

By base ingredient

**Comment by ethanlonge** [comment]
Would it be possible for filtering by primary alcohol (eg. Gin, Vodka, etc.). The only problem is that ingredients would then have to be able to be marked accordingly

**Comment by karlomikus** [comment]
Yeah, this is something I was thinking about. It's also possible to use cocktail_ingredient `sort` attribute and take the first ingredient as primary ingredient. I'll do some testing.

Thanks for contributing!
