### ISSUE TITLE
Shelf header now wraps to a second line.

### ISSUE THREAD

**Issue by reefland** [karlomikus/bar-assistant#380]
- [x ] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
Shelf header now wraps to a second line.

**Versions:**
 - Salt Rim: v3.6.0
 - Bar Assistant: v4.2.4

Would like this to resize down to a single row of stats:
![image](https://github.com/user-attachments/assets/78bca4c6-45c1-4934-aadd-06edd68fd1d3)

**Comment by karlomikus** [comment]
Hello, not a bug, it was made with intent to wrap to second line if needed.

**Comment by reefland** [comment]
OK, not a bug, design issue maybe? There isn't a way to make it one line.  Making the window bigger doesn't help, reducing the font size doesn't help.

**Comment by karlomikus** [comment]
I get what you mean but not an issue. There will be possibly more stats in the future, and the line break heavily depends on selected language and available numbers
