### ISSUE TITLE
Unique cocktail menu for any bar

### ISSUE THREAD

**Issue by mostepunk** [karlomikus/bar-assistant#382]
**Checklist**
- [X] I have checked that this feature is not already requested
- [X] I have checked that this feature does not already exist in the project

**Is your feature request related to a problem? Please describe.**
I have two bars: in my apartment and in my country house. It would be nice to have unique cocktails menu, but items of bar is separate. When I'm adding new cocktail, it should be available in apartment bar and in country house bar without copying the recipe.
At the moment I separate my bars as "Bar shelf"(as country house bar) and "My shelf" (as apartment bar). But this is not the purpose of the features. 

I'd like to help you, but I'm a python backend developer if you need some kind of my help please tell me.

P.S.
Sorry for my broken English :)

**Comment by karlomikus** [comment]
Hello,
Having one menu spanning over multiple bars is not really something that is easily doable and I don't thing it will bring a lot of usefulness to the app.
Similarly, adding one recipe to multiple bars is complicated due to various code constraints, and if that is required importing recipe is viable workaround atm.

**Comment by mostepunk** [comment]
My mistake was that I didn't study the project enough before I proposed the feature.
I think making your own shelves would be a good idea for this. 

You should create tables:
- shelves (slug, name, user_id ...)
- shelf_ingredient (m2m table: ingredient_id, shelf_id)

User can create number of its own shelves (not only bar and own shelves) with separate names. With table shelf_ingredient user can connect ingredient to his created shelf.

After this, the user can:
- know on which shelf a particular ingredient is located. 
- read/remove ingredients from his shelves
- create as many shelves as user needs
- the user is not limited to just two shelves (Bar shelf and My shelf)

**Comment by mostepunk** [comment]
@karlomikus, what do you think about my decision?

**Comment by karlomikus** [comment]
My initial idea when I added bar shelf was to actually add multiple user shelfs but the issues with that is how to handle them on client.
Currently user/bar shelfs are used for a lot of stuff like filtering, calculating missing ingredients, ingredient recommendations and creating a good UX for that is a bit difficult.
I still like the idea of multiple inventories but I think it will be probably for some future major release.

**Comment by mostepunk** [comment]
If any help is needed, I will be happy to take part
