### ISSUE TITLE
Missing Ingredients filter broken

### ISSUE THREAD

**Issue by dphildebrandt** [karlomikus/bar-assistant#383]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
Go to `Cocktails` and filter by `Missing Ingredients` selecting 1, 2, or >=3. In all cases, the results are just incorrect.  There seems to be no rhyme or reason. 

**To Reproduce**
For example I select `2` 
![image](https://github.com/user-attachments/assets/6ecd4089-0976-4376-9b41-dca644737e60)
It lists things like Screwdriver and gemist
![image](https://github.com/user-attachments/assets/3d2c01ac-2c78-44ec-a0db-fe86fd18af9b)
But when I open them up I have all the ingredients
![image](https://github.com/user-attachments/assets/aed3f451-9158-4d37-a615-97e904ad0fe0)
![image](https://github.com/user-attachments/assets/92a0a0c7-f4b0-4c04-97da-935ca776c9e1)
Whereas others might have 1 or 2 ingredients missing as well
![image](https://github.com/user-attachments/assets/86b39648-f037-4a0f-8439-7daed3f0cf9f)
![image](https://github.com/user-attachments/assets/da148656-f21d-4d59-809a-4b94eaf92f65)

Selecting `1` brings up no results despite the previous Mimosa only missing one
![image](https://github.com/user-attachments/assets/72d87486-ec13-46ee-9065-97c062cdacd7)

**Versions:**
 - Bar Assistant: v4.2.4
 - Salt Rim: v3.6.0
 - Browser: chrome

**Comment by karlomikus** [comment]
I've added missing ingredients by bar shelf filter. But currently it will not count complex ingredients and substitutes

**Comment by dphildebrandt** [comment]
@karlomikus can confirms it's working (and almost submitted an issue for the complex ingredients/substitutions 😅)

**Comment by karlomikus** [comment]
Yeah, it's a bit difficult to count complex/substitute ingredients in the current filtering query
