### ISSUE TITLE
Substitutions adversely affecting bar shelf cocktails filter?

### ISSUE THREAD

**Issue by dphildebrandt** [karlomikus/bar-assistant#386]
- [X] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
When a recipe has a substitution but another ingredient missing, it will show up in your bar shelf cocktails anyways. 

**To Reproduce**
Create a cocktail with 2 ingredients missing but one has a substitution. 

![image](https://github.com/user-attachments/assets/2f20b2e1-327a-49c2-8f3d-8798505e80ae)

For example, if you remove the grand marnier substitutions, then it correctly recognizes it as **not** part of your bar shelf cocktails. But with the substitution it fails to notice absinthe is still missing and not valid for bar shelf cocktails.

Maybe it counts 2 missing ingredients but the math with various other substitutions is messing it up?

**Versions:**
 - Bar Assistant: v4.2.4
 - Salt Rim: v3.6.1
 - Browser: chrome

**Comment by dphildebrandt** [comment]
Ah I have another hint, a simpler recipe 

![image](https://github.com/user-attachments/assets/a0b5963f-27cc-45ea-b2df-1b65fd451d00)

This shows up in the Bar Shelf Cocktails despite missing an ingredient. 

If I edit the recipe and remove one of the substitutions for Grand Marnier, then it filters out correctly. 

It seems to be double counting the Grand Marnier substitution since I  have both Triple Sec and Cointreau.

**Comment by karlomikus** [comment]
You're right, its counting total number of substitutes + rest of ingredients, and then it comes to discrepancy between your shelf and cocktail ingredients.

It looks like I'll have to completely refactor the query used for matching.

**Comment by karlomikus** [comment]
Let me know if this is fixed with the newest update

**Comment by dphildebrandt** [comment]
@karlomikus sadly, no, issue still persists

**Comment by karlomikus** [comment]
Hi, please check again it with the latest release :)

**Comment by dphildebrandt** [comment]
@karlomikus Fixed! Thanks for your hard work! ❤️
