### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by albanobattistella** [karlomikus/bar-assistant#390]
**Checklist**
- [ ] I have checked that this feature is not already requested
- [ ] I have checked that this feature does not already exist in the project

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I'm frustrated when I try to [action], but [obstacle]."

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Example: "I would like [desired feature] so that [benefit]."

**Additional context**
Add any other context or screenshots about the feature request here. Example: "Here's an example of how this feature is implemented in [related tool or app]."

**Comment by karlomikus** [comment]
Hello,
Translations are [available via salt-rim web client](https://github.com/karlomikus/vue-salt-rim).

Having language specific data-entry via API is out of scope for this project.
