### ISSUE TITLE
Add cocktail export in json+ld format

### ISSUE THREAD

**Issue by karlomikus** [karlomikus/bar-assistant#42]
- [ ] Add `/cocktails/{public-guid}/ld-json` endpoint
- Add migrations
    - [ ] Create columns: `id_public`

**Comment by zhdenny** [comment]
Can this somehow also be made to support bulk selection? Like being able to select multiple cocktails or all cocktails? And of course the associated ingredients carry over if missing.

And I'm assuming this feature would have no way of also supporting the associated cocktail/ingredients photos? Bummer but so glad you are working on this.

Great feature. Thanks
