### ISSUE TITLE
[Feature Request] Reverse Proxy enchancement

### ISSUE THREAD

**Issue by FonduemangVI** [karlomikus/bar-assistant#59]
Hi. I'm not sure if this should be logged here or on the BA GH. 

However would it be possible to make it, so you only need to reverse proxy the GUI frontend and not also have to RP the BA server and Meilsearch. This would be much better from a security standpoint as well if exposing the instance publicly which I would like to do

**Comment by chupacabra71** [comment]
I'm kind of a noob at this, but couldn't we create an overlay network just for bar assistant.  I think that (in theory) this would let the containers talk to each-other and then we would just need to publish the external ports?  i may be way off base though.

**Comment by zhdenny** [comment]
I'm not docker savvy enough to know about any of that personally.
For now, I've just been reverse proxy'ing both Bar Assistant and Salt Rim.

If you figure it out, post up how. Would be awesome

**Comment by karlomikus** [comment]
> I'm kind of a noob at this, but couldn't we create an overlay network just for bar assistant. I think that (in theory) this would let the containers talk to each-other and then we would just need to publish the external ports? i may be way off base though.

I'm working on something similar here: https://github.com/bar-assistant/docker/blob/new_config/nginx.conf
This will proxy all services to "subdirectory" paths so they can all be on a single port.

**Comment by karlomikus** [comment]
You need to expose only one service since version 1.5, you can [find the new guide here](https://bar-assistant.github.io/docs/setup/).

If you are still having problems please open a new issue.
