### ISSUE TITLE
Docker image improvements

### ISSUE THREAD

**Issue by karlomikus** [karlomikus/bar-assistant#60]
- [x] Switch to PHP-FPM image variant
- [ ] ~Include meilisearch instance in base BA image~
- [x] Add empty volume for BA data
    - [x] Move uploads folder and db file to this folder
- [x] Add nginx as default reverse proxy
- [x] Add services by path in a another nginx instance
    - /search for meilisearch, /bar for api
    - Update code to handle this changes
- [x] Use nginx to serve static files for salt-rim
- [Optional] Create a single container image based on alpine

This should hopefully simplify deployment.

Related issues: #12 #26 #37 #50 #59

https://github.com/bar-assistant/docker/pull/2

**Comment by zhdenny** [comment]
This sounds like a pretty big update/upgrade for docker users.

Could you include any special upgrade instructions when this is released. Like path changes or docker compose changes etc.

Awesome work man!

**Comment by karlomikus** [comment]
Before all this I will iron out application backup and import features.
Ideally this will not be a huge change to user's docker settings but we will see :D

**Comment by kavemang** [comment]
I'm trying a bunch of variations of localhost:8000 but can't seem to get salt-rim to talk to the api server, the other containers seem to link up fine, stumped so far

**Comment by zhdenny** [comment]
Open a separate issue and provide your full docker compose file.

**Comment by damian-w** [comment]
+1 for the suggestion to a merge everything into a single container image based on alpine

**Comment by karlomikus** [comment]
> +1 for the suggestion to a merge everything into a single container image based on alpine

This was something I planned to do from the start but it kinda goes against the whole containerization principle. But I will definitely simplify redis and meilisearch dependencies.

**Comment by tscibilia** [comment]
I tried the new docker info you referenced in this PR https://github.com/bar-assistant/docker/pull/2 but it's still not connecting to the bar assistant server. I'm seeing a "Status: Not available" on the frontend login screen

**Comment by karlomikus** [comment]
> I tried the new docker info you referenced in this PR [bar-assistant/docker#2](https://github.com/bar-assistant/docker/pull/2) but it's still not connecting to the bar assistant server. I'm seeing a "Status: Not available" on the frontend login screen

That is still work in progress, and I still haven't released any images for that branch.

But that should be done by the end of this month
