### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by raddacle** [karlomikus/bar-assistant#64]
I've setup a new docker install. When I create an ingredient or cocktail, it does show "1 ingredient" on the home screen, but when I click on that the Ingredients page is empty. I can't figure out whats going on here, any ideas?

**Comment by karlomikus** [comment]
This sounds like an issue with a your meilisearch instance. Can you check your browser console for errors?

**Comment by kavemang** [comment]
also having this issue after getting the docker stack connected and running

**Comment by karlomikus** [comment]
I can't really help you there, this looks like you have some configuration issues. Be sure to check logs.

BA logs can be found @ `/var/www/cocktails/storage/logs/laravel.log` inside the container
Meilisearch logs should be available with `docker compose logs`

**Comment by karlomikus** [comment]
New docker improvements are now available as a release candidate.
I welcome you to try the new setup, you can [find the guide here](https://bar-assistant.github.io/docs/setup/).

If you are still having problems please open a new issue.
