### ISSUE TITLE
Reverse Proxy cannot connect to Bar Assistant

### ISSUE THREAD

**Issue by phantomdez** [karlomikus/bar-assistant#65]
Hopefully this is just a config issue on my end but I am hoping you might be able to clarify for me.  So I setup the docker build provided in your documentation and got everything working as required and I was able to login using the server URL [http://myserver.local:8080].  When I setup my reverse proxy and pointed to said address and I go to the site I get: 

Bar Assistant server:
http://myserver.local:8000
Status: Not available

However the URL http://myserver.local:8080 works just fine.  I am guessing there is some special configuration that I need to apply to allow access to port 8000 for the bar-assistant server.

Also a couple of notes about your Complete Docker Install.  
1.  The default login that is listed doesn't work.  I registered a user and then from the server side promoted that user to admin.
2. Not sure why but when I specified localhost in the environment variables I got a Not Available message.  When I updated to the server DNS name it started connecting.  I a guessing this is because its not running on my local machine

**Comment by karlomikus** [comment]
Looks like you have a typo, your working instance is on port `8080` not `8000`.

Related to the notes:
- Default login is created with arguments from `https://github.com/karlomikus/bar-assistant/blob/master/app/Console/Commands/BarOpen.php#L30`, the defaults are: admin@example.com and password.
- You must be able to visit your BA instance from your browser for salt-rim to work, so using localhost as a URL is depended on your setup

I'm successfully using traefik reverse proxy for my instances, so I can maybe help with some config options.

**Comment by phantomdez** [comment]
I did the docker-compose install listed here: https://github.com/bar-assistant/docker

After the install it asked me to register a user.  I setup my account and then promoted via the CLI to admin.  There were no other accounts on the server.  Is the docker image suppose to create an admin@example.com account by default as mine did not.

As for the reverse proxy issue are you saying that my browser needs to access the bar assistant server as well as the Salt-rim server directly?  Salt-rim listens on 8080 but bar-assistant listens on 8000 which is why I am confused why it wouldn't work through the proxy.  They way I have it configured is that my URL points to a Virtual IP which then points to the backend server [Salt-rim]  However Salt-rim shows an error message when I use the Proxied URL that the real server name isn't accessible.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/56058726/216746893-885da889-7a19-4885-bc47-756fd1084121.png">

vs when I go to real server with port 8080.  

<img width="372" alt="image" src="https://user-images.githubusercontent.com/56058726/216746938-5e9b0cdb-1679-48df-989c-8e3e1bcd31bc.png">

**Comment by karlomikus** [comment]
I think the easiest way is to setup reverse proxy for each service, and see if you can access it from your browser. Then you can setup .env variables accordingly.

**Comment by zhdenny** [comment]
See here....
https://github.com/karlomikus/bar-assistant/issues/59

If you want to Reverse Proxy in order to Expose SaltRim externally, Make sure you reverse proxy not only SaltRim but also Meilisearch and BarAssistant.

**Comment by karlomikus** [comment]
New docker improvements are now available as a release candidate.
I welcome you to try the new setup, you can [find the guide here](https://bar-assistant.github.io/docs/setup/).

If you are still having problems please open a new issue.
