### ISSUE TITLE
Server Error when creating new Cocktail

### ISSUE THREAD

**Issue by Ralf-J** [karlomikus/bar-assistant#77]
I did a fresh install using the deocumented Docker approach. Everything worked fine: could create new users, deleted the default user, was able to create new ingredients and uploading their pictures. However, when creating a new cocktail, I just get a pop-up saying "Server Error" as soon as I click on the "Save" button. To test, I tried to edit an existing recipe. This worked fine.

What could be the reason that I can change existing recipes of cocktails, can create new ingredients, but can not create a cocktail?

**Comment by karlomikus** [comment]
There should be some error logs in docker.

Run the following command:
```
$ docker compose logs bar-assistant --tail 200 -f
```

Then try to add the cocktail, there should be some kind of error displayed

**Comment by Ralf-J** [comment]
Thanks for the reply. I meanwhile tested a little bit more and can now reproduce the error. I added the cocktail step by step, i.e. whenever I added a description, a picture, an ingredient, etc. I saved. Worked all fine until I added a bitter where for "amount" I used "dashes". This is something for some cocktails prefilled in the database it is used. But it is not possible to add a new cocktail with "dashes" as amount. Whenever I changed for the very same ingredient the amount to something like e.g. cl or ml it worked. So seems that not all units are allowed to enter new althought they are standards and are used in existing cocktails.

The error that was produced in the log (I deployed the container stack via Portainer so used their logging function, should be ok I hope):

[2023-02-26 12:39:27] production.ERROR: Kami\Cocktail\DataObjects\Ingredient::__construct(): Argument #3 ($amount) must be of type float, string given, called in /var/www/cocktails/app/Http/Controllers/CocktailController.php on line 148 {"userId":3,"exception":"[object] (TypeError(code: 0): Kami\\Cocktail\\DataObjects\\Ingredient::__construct(): Argument #3 ($amount) must be of type float, string given, called in /var/www/cocktails/app/Http/Controllers/CocktailController.php on line 148 at /var/www/cocktails/app/DataObjects/Ingredient.php:9)

**Comment by zhdenny** [comment]
So interesting the error only occurs with "dashes". I can reproduce this error too.

**Comment by Ralf-J** [comment]
Yes, but not only for "dashes". For example the prefilled Cocktail "Bacardi Cocktail" includes in the ingredients 1 "barspoon". When trying to use this in a new Cocktail, I get the same error. So seems whenever something elsa than "oz", "cl" or "ml" is used, the error is coming up.

**Comment by karlomikus** [comment]
Confirmed, will be fixed. Thanks!
