### ISSUE TITLE
Cocktails I can make filter not working: invalid_search_filter

### ISSUE THREAD

**Issue by ovv** [karlomikus/bar-assistant#88]
Hello, on my instance the "cocktails I can make" filter is not working and produce an error.

The request is a `POST` on `/search/indexes/cocktails/search` that returns a 400

Request payload:
```
{"q":"","facets":["tags","user_id","has_public_link","average_rating","main_ingredient_name","method","glass"],"attributesToHighlight":["*"],"highlightPreTag":"__ais-highlight__","highlightPostTag":"__/ais-highlight__","limit":101,"filter":["id IN [[object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]]"],"sort":["name:asc"]}
```

Request response:
```
{"message":"Expected only comma-separated field names inside `IN[..]` but instead found `[object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]]`.\n8:143 id IN [[object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]]","code":"invalid_search_filter","type":"invalid_request","link":"https://docs.meilisearch.com/errors#invalid_search_filter"}
```

**Comment by karlomikus** [comment]
Hello,
This looks like a bug, can you add some more info:

- What is the browser on which this happens?
- What is your Meilisearch instance version?
- Also there should be a call to `/api/cocktails/user-shelf?format=ids` on cocktails list page load, can you also check the response body?

Thanks

**Comment by ovv** [comment]
Thanks for pointing out `/api/cocktails/user-shelf?format=ids` I was able to figure it out.

My server was misconfigured, and the request query wasn't taken into account. `/api/cocktails/user-shelf?format=ids` was returning the full JSON object for each item and not an array of IDs. Fixing my configuration made `/api/cocktails/user-shelf?format=ids` return an array of ID and the correct value are then sent to `/search/indexes/cocktails/search`.
