### ISSUE TITLE
Suggestion: Allow users to see the ingredients on their shelf

### ISSUE THREAD

**Issue by augustf** [karlomikus/bar-assistant#94]
Once a user adds an ingredient to their shelf, there's no way to get a list of those again in the application. Bar Assistant should expose an API endpoint that returns all the ingredients a user has on their shelf, such that Salt Rim can expose that data, either directly on the Shelf page, or via the Search area under Ingredients.

**Comment by augustf** [comment]
Getting the dev code up and running and messing around, it struck me that taking a user parameter in the Ingredient controller (https://github.com/karlomikus/bar-assistant/blob/master/app/Http/Controllers/IngredientController.php#L30) to achieve this might be possible, but a few hours of messing around with a framework I'm unfamiliar with didn't yield an immediately working way of making this happen.

**Comment by karlomikus** [comment]
Hello,
This is definitely missing in api responses, thanks!
Also, in latest version of Salt Rim you can filter shelf ingredients.

**Comment by augustf** [comment]
Oh wow-I hadn't seen 1.9.0 became available. The shelf filter feature is exactly what was needed. Having this call in the API is probably not super useful then, except for pulling shelf ingredients for other scripts/integrations.
